[package]
name = "led-scroll"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7.7"
cortex-m-rt = "0.7.3"
embedded-hal = "1.0.0"
microbit-v2 = "0.15.0"
nrf52833-hal = "0.18.0"
nrf52833-pac = "0.12.2"
# panic-halt = "0.2.0"
